name: Hello new day

on:
  schedule:
    - cron: "1 0 * * *"

jobs:
  midnight-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          template: "templates/sadikkuzu.tpl"
          writeTo: "README.md"

      - uses: actions/upload-artifact@v3
        with:
          name: README.md
          path: README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Hello new day!
          branch: master
          commit_user_name: nights watch 🤖
          commit_user_email: sadikkuzu@hotmail.com
          commit_author: nights watch 🤖 <sadikkuzu@hotmail.com>
