name: Update sadikkuzu README

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 1-23 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          template: "templates/sadikkuzu.tpl"
          writeTo: "README.md"

      - uses: actions/upload-artifact@v1
        with:
          name: README.md
          path: README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated sadikkuzu readme
          branch: master
          commit_user_name: readme-scribe 🤖
          commit_user_email: sadikkuzu@hotmail.com
          commit_author: readme-scribe 🤖 <sadikkuzu@hotmail.com>
